# Generated by Django 3.0.5 on 2020-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Machine', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Availability', models.BooleanField()),
            ],
        ),
    ]
