# Generated by Django 3.0.5 on 2020-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200417_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='Price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
